spring:
  application:
    name: adminserver

server:
  port: 8889
  servlet:
    context-path: /admin

eureka:   
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int} 
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'  
  endpoint:
    health:
      show-details: ALWAYS
