spring:
  application:
    name: discovery
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: https://github.com/albertisco/springcloud-config
    register-with-eureka: false
    fetch-registry: false
