spring:
  application:
    name: gymapp
server:
  port: 8084
eureka:
  instance:
    preferIpAddress: true
  client:
    region: default
    registryFetchIntervalSeconds: 15
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
