spring:
  application:
    name: gymapp
  boot:
    admin:
      client:
        url: http://localhost:8889
        
management:
  endpoints:
    web:
      exposure:
        include: '*'  
  endpoint:
    health:
      show-details: ALWAYS
      
server:
  port: 8085
  servlet:
    context-path: /gymapp
    
eureka:
  instance:
    preferIpAddress: true
  client:
    region: default
    registryFetchIntervalSeconds: 15
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
