server:
  port: 8888

spring:
  application:
    name: zuulproxyserver
  cloud:
    gateway:
      routes:
      - id: gymapp
        uri: lb://GYMAPP
        predicates:
        - Path=/gymapp/**
      - id: serviciosaludo
        uri: lb://SERVICIOSALUDO
        predicates:
        - Path=/serviciosaludo/**
        
management:
  endpoints:
    web:
      exposure:
        include: '*'  
  endpoint:
    health:
      show-details: ALWAYS
 
eureka:
  instance:
    preferIpAddress: true
  client:
    region: default
    registryFetchIntervalSeconds: 15
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
  

 

