server:
  port: 8888

spring:
  application:
    name: zuulproxyserver
    
management:
  endpoints:
    web:
      exposure:
        include: *
 
eureka:
  instance:
    preferIpAddress: true
  client:
    region: default
    registryFetchIntervalSeconds: 15
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
  

 

